BUG_NAME=pyt_20288
CLIENT_MANUAL_DEPENDENCY=91ea2cd
EVALUATION_TYPE=corrected
CLIENT_PY_VERSION=3.5.6
MODEL_LIBRARY=pytorch
CLIENT_LOG_DIR=/results/client
NUMBER_OF_RUNS=2
PY_CACHE_DIR=/pip-cache
DATA_SERVER_ENDPOINT=tcp://172.17.0.2:90002
USE_BUILD_MKL=1
USE_CUDA=True
